name: PROXY Updater

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyfiglet colorama

    - name: Write source code to file
      run: echo "${{ secrets.SOURCE_CODE }}" > updater.py

    - name: Run updater.py
      run: python updater.py

    - name: Remove updater.py
      run: rm updater.py

    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.EMAIL }}
        git config --local user.name ${{ secrets.NAME }}
        git add .
        git commit -m "Updated Proxies"
        git push

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
      env:
        CI: true
